flyway.url=jdbc:postgresql://localhost:5432/billpayworkerdb
flyway.user=postgres
flyway.password=1
flyway.schemas=public
flyway.locations=filesystem:migration/billpayworkerdb
flyway.validateMigrationNaming=true
