flyway.url=jdbc:postgresql://localhost:5432/customerdb
flyway.user=postgres
flyway.password=1
flyway.schemas=public
flyway.locations=filesystem:migration/customerdb
flyway.validateMigrationNaming=true
