flyway.url=jdbc:postgresql://localhost:5432/accountsdb
flyway.user=postgres
flyway.password=1
flyway.schemas=public
flyway.locations=filesystem:migration/accountsdb
flyway.validateMigrationNaming=true
