flyway.url=jdbc:postgresql://localhost:5432/settlementdb
flyway.user=postgres
flyway.password=1
flyway.schemas=public
flyway.locations=filesystem:migration/settlementdb
flyway.validateMigrationNaming=true
